export const studio = {
  name: 'SattvaFlow',
  tagline: 'Holistic · Body & Soul',
  description: 'Yoga, movement, healing, and gatherings — tended in Jūrmala.',
  highlight1: 'Memberships & drop-ins · +371 26835974',
  highlight2: 'Bookings via Fresha',
  phone: '+37126835974',
  whatsapp: '+37126835974',
  email: '',
  address: 'Jomas iela 56, Jūrmala',
  addressShort: 'Jomas 56, Jūrmala',
  instagram: 'https://instagram.com/sattva_flow',
  instagramHandle: '@sattva_flow',
  freshaUrl: '',
  mapsLink: 'https://maps.google.com/?q=Jomas+iela+56+Jurmala',
  mapsEmbed:
    'https://maps.google.com/maps?q=Jomas+iela+56+Jurmala&t=&z=16&ie=UTF8&iwloc=&output=embed',
  hours: {
    weekday: 'Mon – Fri: 9:00 – 21:00',
    friday: 'Sat – Sun: 10:00 – 19:00',
    sunday: 'Bookings: Fresha',
  },
  heroVideo: '/videos/hero.mp4',
  heroVideoStart: 0,
  aboutVideo: '/videos/interior.mp4',
  cinematicVideo: '/videos/hero.mp4',
  rentalVideos: ['/noma/telpunoma1.mp4', '/noma/telpunoma2.mp4'],
  colors: {
    primary: '#B8826F',
    primaryDark: '#2C2420',
    bg: '#FEFCF8',
    bgAlt: '#F5EDE0',
    text: '#2C2420',
    gray: '#6B5D53',
  },
  menu: {
    Movement: [
      { name: 'Hatha Yoga', desc: 'Gentle, foundational yoga', price: '€15', img: '/images/class-hatha.jpg' },
      { name: 'Vinyasa Flow', desc: 'Dynamic breath-linked flow', price: '€15', img: '/images/class-vinyasa.jpg' },
      { name: 'Fly Yoga', desc: 'Antigravity in silk hammocks', price: '€20', img: '/images/class-fly.jpg' },
    ],
    Healing: [
      { name: 'Sound Healing', desc: 'Sound bath with bowls & handpan', price: '€25', img: '/images/class-sound.jpg' },
      { name: 'Massage', desc: 'Therapeutic & relaxation', price: 'From €50', img: '/images/class-massage.jpg' },
      { name: 'Ayurveda', desc: 'Personal consultation', price: 'From €60', img: '/images/class-ayurveda.jpg' },
    ],
    Gatherings: [
      { name: 'Workshops', desc: 'Deep-dive sessions', price: '—', img: '/images/class-workshop.jpg' },
      { name: 'Retreats', desc: 'Multi-day immersions', price: '—', img: '/images/class-retreat.jpg' },
      { name: 'Sound Journeys', desc: 'Full sound bath events', price: '—', img: '/images/class-journey.jpg' },
    ],
  },
  menuImages: [
    '/images/1.jpg','/images/2.jpg','/images/3.jpg','/images/4.jpg',
    '/images/5.jpg','/images/6.jpg','/images/7.jpg','/images/8.jpg',
    '/images/9.jpg','/images/10.jpg','/images/11.jpg','/images/12.jpg',
    '/images/13.jpg','/images/14.jpg',
  ],
  reviews: [
    { stars: 5, text: 'Found my way back to my body here. Vinyasa is exactly what I needed — strong but gentle.', name: 'Anna K.', time: '2 weeks ago', tags: ['Vinyasa', 'Regular'] },
    { stars: 5, text: 'Sound healing left me feeling like I\'d been gone for a year. Incredible space.', name: 'Māris B.', time: '1 month ago', tags: ['Sound Healing'] },
    { stars: 5, text: 'Fly Yoga is addictive. Being in a silk hammock is the most fun I\'ve had in years.', name: 'Ieva S.', time: '3 days ago', tags: ['Fly Yoga'] },
    { stars: 5, text: 'The space is warm, the teachers read the room, I always leave lighter.', name: 'Jānis R.', time: '2 months ago', tags: ['Atmosphere'] },
    { stars: 5, text: 'Tried barre on a whim — now it\'s my Monday ritual.', name: 'Laura M.', time: '1 week ago', tags: ['Barre'] },
    { stars: 5, text: 'Art therapy here helped me through a hard season. Kind and genuinely healing.', name: 'Rihards T.', time: '3 months ago', tags: ['Art Therapy'] },
  ],
  pillars: [
    { slug: 'movement', title: 'Movement', description: 'Yoga, dance, barre, stretch.' },
    { slug: 'healing', title: 'Healing', description: 'Ayurveda, sound healing, massage.' },
    { slug: 'mind', title: 'Mind', description: 'Art therapy, psychotherapy.' },
    { slug: 'gatherings', title: 'Gatherings', description: 'Seminars, workshops, retreats.' },
  ],
  classes: [
    { slug: 'hatha-yoga', name: 'Hatha Yoga', pillar: 'movement', duration: '60 min', level: 'All levels', price: '€15', description: 'Gentle, foundational yoga — postures held longer, with emphasis on breath and alignment.' },
    { slug: 'vinyasa-flow', name: 'Vinyasa Flow', pillar: 'movement', duration: '75 min', level: 'Intermediate', price: '€15', description: 'Dynamic, breath-linked sequences. Builds heat, strength, fluidity.' },
    { slug: 'fly-yoga', name: 'Fly Yoga', pillar: 'movement', duration: '60 min', level: 'All levels', price: '€20', description: 'Antigravity yoga using silk hammocks. Decompresses the spine.' },
    { slug: 'barre', name: 'Barre', pillar: 'movement', duration: '60 min', level: 'All levels', price: '€15', description: 'Ballet-inspired conditioning. Low impact, high burn.' },
    { slug: 'dance', name: 'Dance', pillar: 'movement', duration: '60 min', level: 'All levels', price: '€15', description: 'Free-form movement and choreography.' },
    { slug: 'stretching', name: 'Stretching', pillar: 'movement', duration: '60 min', level: 'All levels', price: '€15', description: 'Deep passive and active stretching.' },
    { slug: 'tai-chi-qigong', name: 'Tai Chi & Qi Gong', pillar: 'movement', duration: '60 min', level: 'All levels', price: '€15', description: 'Meditative moving practice.' },
    { slug: 'sound-healing', name: 'Sound Healing', pillar: 'healing', duration: '60 min', level: 'All levels', price: '€25', description: 'Immersive sound bath with singing bowls and handpan.' },
    { slug: 'massage', name: 'Massage', pillar: 'healing', duration: '60–90 min', level: 'By appointment', price: 'From €50', description: 'Therapeutic and relaxation massage.' },
    { slug: 'ayurveda', name: 'Ayurveda Consultation', pillar: 'healing', duration: '90 min', level: 'By appointment', price: 'From €60', description: 'Personal Ayurvedic consultation.' },
    { slug: 'art-therapy', name: 'Art Therapy', pillar: 'mind', duration: '60 min', level: 'By appointment', price: 'From €45', description: 'Process emotions through creative expression.' },
    { slug: 'psychotherapy', name: 'Psychotherapy', pillar: 'mind', duration: '50 min', level: 'By appointment', price: 'From €50', description: 'Confidential one-to-one psychotherapy.' },
  ],
  scheduleMonth: 'April',
  schedule: [
    { day: 'Monday', entries: [
      { time: '8:50 – 9:50', class: 'Barre', teacher: 'Irina' },
      { time: '10:00 – 11:30', class: 'Yoga', teacher: 'Santa' },
      { time: '18:00 – 19:00', class: 'Dance', teacher: 'Annila' },
      { time: '20:00 – 21:00', class: 'Dance', teacher: 'Annila' },
    ]},
    { day: 'Tuesday', entries: [
      { time: '9:00 – 10:00', class: 'Fitness', teacher: 'Marija' },
      { time: '10:15 – 11:45', class: 'Yoga for Beginners', teacher: 'Juliana' },
      { time: '14:00 – 15:30', class: 'Yoga for Kids' },
      { time: '16:00 – 17:00', class: 'Tai Chi', teacher: 'Igor' },
      { time: '17:00 – 18:00', class: 'Hang School' },
      { time: '18:30 – 20:00', class: 'Hatha Yoga', teacher: 'Iveta' },
    ]},
    { day: 'Wednesday', entries: [
      { time: '9:00 – 11:00', class: 'Barre / Stretching', teacher: 'Irina' },
      { time: '11:30 – 13:00', class: 'Tai Chi', teacher: 'Marija' },
      { time: '15:00 – 16:30', class: 'Fly Yoga for Kids' },
      { time: '18:00 – 19:30', class: 'Yoga', teacher: 'Nelly' },
      { time: '20:00 – 21:00', class: 'Dance', teacher: 'Anila' },
    ]},
    { day: 'Thursday', entries: [
      { time: '6:00 – 7:30', class: 'Kriya Yoga', teacher: 'Dipika' },
      { time: '9:15 – 10:30', class: 'Fitness', teacher: 'Marija' },
      { time: '10:30 – 11:50', class: 'Vinyasa Yoga', teacher: 'Santa' },
      { time: '12:00 – 18:00', class: 'Massage', teacher: 'Kristina' },
      { time: '17:30 – 19:00', class: 'Hatha Yoga', teacher: 'Iveta' },
      { time: '18:30 – 20:00', class: 'Antigravity Yoga + Sound Healing', teacher: 'Juliana' },
    ]},
    { day: 'Friday', entries: [
      { time: '9:00 – 12:00', class: 'Barre / Stretching', teacher: 'Irina' },
      { time: '12:15 – 19:00', class: 'Massage', teacher: 'Natalya' },
      { time: '19:00 – 21:00', class: 'Antigravity + Flow Dance + Sound Healing', teacher: 'Juliana' },
    ]},
    { day: 'Saturday', entries: [
      { time: '9:00 – 10:30', class: 'Vinyasa Yoga', teacher: 'Santa' },
      { time: '10:30 – 12:00', class: 'Yoga', teacher: 'Nelli' },
      { time: '19:00 – 20:30', class: 'Antigravity Yoga' },
      { time: '20:30 – 22:00', class: 'Flow Meditation Dance + Sound Healing' },
    ]},
    { day: 'Sunday', entries: [
      { time: '10:00 – 11:30', class: 'Yoga for Beginners + Antigravity', teacher: 'Juliana' },
      { time: '12:00 – 13:00', class: 'Hang — Ethnic Instruments School' },
    ]},
  ],
  faqs: [
    { q: 'I have never done yoga before — is that okay?', a: 'Absolutely. Most classes are all-levels. Hatha Yoga and Stretching are the easiest starting points.' },
    { q: 'Do I need to book in advance?', a: 'For group classes, walk-ins are welcome but booking ahead guarantees your spot. Individual sessions must be booked.' },
    { q: 'What should I bring?', a: 'Comfortable clothing and water. We provide mats, blocks, bolsters, and straps.' },
    { q: 'Can I pay per class, or do I need a membership?', a: 'Both. Drop-ins are welcome. Class packs and monthly memberships offer better value for regulars.' },
    { q: 'What language are classes in?', a: 'Latvian, English, and Russian — teachers switch based on who\'s in the room.' },
    { q: 'Where do I change?', a: 'Changing areas are on-site. We recommend arriving ready if possible.' },
    { q: 'Is there parking?', a: 'Street parking is available on Jomas iela.' },
  ],
  announcements: [
    { date: '2026-04-22', title: 'Irina on vacation', body: 'Teacher Irina is away from April 25 to May 10. Barre and Stretching classes will be covered by substitute teachers — check the schedule or Instagram for updates.' },
    { date: '2026-04-18', title: 'New: Antigravity + Sound Healing', body: 'A new combined class every Thursday evening with Juliana — antigravity flow followed by a sound bath. Limited hammocks, book ahead.' },
  ] as { date: string; title: string; body: string }[],
  teachers: [
    { name: 'Irina', specialties: ['Barre', 'Stretching'] },
    { name: 'Santa', specialties: ['Vinyasa Yoga', 'Hatha Yoga'] },
    { name: 'Juliana', specialties: ['Yoga for Beginners', 'Antigravity', 'Sound Healing'] },
    { name: 'Iveta', specialties: ['Hatha Yoga'] },
    { name: 'Nelly', specialties: ['Yoga'] },
    { name: 'Marija', specialties: ['Fitness', 'Tai Chi'] },
    { name: 'Igor', specialties: ['Tai Chi'] },
    { name: 'Annila', specialties: ['Dance'] },
    { name: 'Dipika', specialties: ['Kriya Yoga'] },
    { name: 'Kristina', specialties: ['Massage'] },
    { name: 'Natalya', specialties: ['Massage'] },
  ],
}

export type Studio = typeof studio
